function csvEscape(val: unknown): string {
  const s = String(val ?? "");
  return s.includes(",") || s.includes('"') || s.includes("\n") ? `"${s.replace(/"/g, '""')}"` : s;
}

export function downloadCSV(filename: string, headers: string[], rows: unknown[][]): void {
  const csv = [headers, ...rows].map((r) => r.map(csvEscape).join(",")).join("\n");
  const blob = new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadPDF(filename: string, title: string, headers: string[], rows: unknown[][]): void {
  const tableRows = rows.map((r) =>
    `<tr>${r.map((c) => `<td style="padding:6px 10px;border:1px solid #ccc;font-size:12px">${csvEscape(c)}</td>`).join("")}</tr>`
  ).join("\n");
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${title}</title></head><body>
    <h2 style="font-family:sans-serif;margin-bottom:16px">${title}</h2>
    <table style="border-collapse:collapse;width:100%;font-family:sans-serif">
      <thead><tr>${headers.map((h) => `<th style="padding:8px 10px;border:1px solid #999;background:#eee;font-size:13px;text-align:left">${h}</th>`).join("")}</tr></thead>
      <tbody>${tableRows}</tbody>
    </table>
    <p style="font-family:sans-serif;font-size:10px;color:#888;margin-top:16px">Generated by Faraz Pharmacy POS</p>
    <script>window.print()<\/script>
  </body></html>`;
  const win = window.open("", "_blank");
  if (win) {
    win.document.write(html);
    win.document.close();
  }
}